apiVersion: v1
kind: Service
metadata:
  name: boatvote-web-service
  namespace: default
spec:
  selector:
    app: boatvote-web-kube
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3000

